version: '3'
services:
  autogenbook:
    image: autogenbook:1.0
    build: .
    volumes:
      - .:/app
    ports:
      - "8100:8100"
    command: uvicorn main:app --host 0.0.0.0 --port 8100 --reload
    environment:
      - PYTHONPATH=/app
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"

