services:
  autogenbook:
    image: autogenbook:1.0
    working_dir: /app
    build: .
    volumes:
      - .:/app    
    command: tail -f /dev/null
    extra_hosts:
      - "host.docker.internal:host-gateway"

